#!/bin/bash

FROM centos
RUN yum -y update && yum -y install \
  git \
  gcc \
  gcc-c++ \
  zlib-devel \
  gtk2-devel \
  glib2-devel \
  libfdt-devel \
  pixman-devel \
  vte-devel \
  libaio-devel \
  libcap-devel \
  libiscsi-devel \
  make \
  gettext \
  bc \
  bison\
  flex\
  rpm \
  rpm-build
