#!/bin/bash

set -eux

BUILD_FOR=${BUILD_FOR:-ubuntu}
DIR="$(dirname `readlink -f $0`)"
MODULES="${DIR}/deployment_scripts/puppet/modules"

REBOOT_VER='1.2.1'
REBOOT_URL="https://github.com/puppetlabs/puppetlabs-reboot/archive/${REBOOT_VER}.tar.gz"

function build_pkg {
  case $1 in
    ubuntu)
      rm -rf repositories/ubuntu; mkdir -p repositories/ubuntu
      sudo docker build -t kvm .

      # run /kvmfornfv/fuel-plugin/build_kvm.sh in docker
      sudo docker run -v ${DIR}/..:/kvmfornfv -t  kvm /kvmfornfv/fuel-plugin/build_kvm.sh
      # debug in console by the following command
      # sudo docker run -v /kvmfornfv:/kvmfornfv -ti  kvm  /bin/bash
      cp ${DIR}/../*.deb repositories/ubuntu
    ;;
    *) echo "Not supported system"; exit 1;;
  esac
}

for system in $BUILD_FOR
do
  build_pkg $system
done

rm -rf ${MODULES}/reboot
mkdir -p ${MODULES}/reboot
wget -qO- ${REBOOT_URL} |  tar -C ${MODULES}/reboot --strip-components=1 -zxvf -
