#!/bin/bash

set -eux

BUILD_FOR=${BUILD_FOR:-ubuntu}
DIR="$(dirname `readlink -f $0`)"
MODULES="${DIR}/deployment_scripts/puppet/modules"

SHELLVAR_VERSION='2.2.1'
AUGCORE_VERSION='2.1.3'

SHELLVAR_URL="https://github.com/hercules-team/augeasproviders_shellvar/archive/${SHELLVAR_VERSION}.tar.gz"
AUGCORE_URL="https://github.com/hercules-team/augeasproviders_core/archive/${AUGCORE_VERSION}.tar.gz"

function build_pkg {
  case $1 in
    ubuntu)
      rm -rf repositories/ubuntu; mkdir -p repositories/ubuntu
      sudo docker build -t kvm .

      # run /kvmfornfv/fuel-plugin/build_kvm.sh in docker
      sudo docker run -v ${DIR}/..:/kvmfornfv -t  kvm /kvmfornfv/fuel-plugin/build_kvm.sh
      # debug in console by the following command
      # sudo docker run -v /kvmfornfv:/kvmfornfv -ti  kvm  /bin/bash
      cp ${DIR}/../*.deb repositories/ubuntu
    ;;
    *) echo "Not supported system"; exit 1;;
  esac
}

for system in $BUILD_FOR
do
  build_pkg $system
done

rm -rf ${MODULES}/*
mkdir -p ${MODULES}/shellvar ${MODULES}/augcore

wget -qO- ${SHELLVAR_URL} | tar -C ${MODULES}/shellvar --strip-components=1 -zxvf -
wget -qO- ${AUGCORE_URL} | tar -C ${MODULES}/augcore --strip-components=1 -zxvf -
