#!/bin/bash

FROM centos
RUN yum -y update && yum -y install \
  git \
  gcc \
  gcc-c++ \
  zlib-devel \
  gtk2-devel \
  glib2-devel \
  make \
  gettext \
  openssl-devel \
  bc \
  bison\
  flex\
  rpm \
  rpm-build