#!/bin/sh
#
#	Output a simple RPM spec file.
#	This version assumes a minimum of RPM 4.0.3.
#
#	The only gothic bit here is redefining install_post to avoid
#	stripping the symbols from files in the kernel which we want
#
#	Patched for non-x86 by Opencon (L) 2002 <opencon@rio.skydome.net>
#

# how we were called determines which rpms we build and how we build them

# starting to output the spec

QEMURELEASE=$1

__QEMURELEASE=`echo $QEMURELEASE | sed -e "s/-/_/g"`

echo $srctree
echo "Name: qemu"
echo "Summary: The Linux qemu"
echo "Version: $__QEMURELEASE"
# we need to determine the NEXT version number so that uname and
# rpm -q will agree
echo "Release: `. ${srctree} scripts/mkversion`"
echo "License: GPL"
echo "Group: System Environment/Kernel"
echo "Vendor: The Linux Community"
echo "URL: http://www.kernel.org"

echo "Source: qemu-$__QEMURELEASE.tar.gz"

echo "%description" 
echo "%prep" 
echo "     " 
echo "%setup -q" 
echo "         " 
echo "%build" 
echo "%_configure" 
echo "make" 
echo "%install" 
echo "rm -rf %{buildroot}" 
echo "make install DESTDIR=%{buildroot}" 
echo "%clean" 
echo "rm -rf %{buildroot}"
echo "%files" 
echo "%dir" 
echo "/usr/local/share/qemu" 
echo "%doc" 
echo "/usr/local/bin/ivshmem*"
echo "/usr/local/bin/qemu*" 
echo "/usr/local/libexec/qemu-bridge-helper" 
echo "%changelog"

